### PR TITLE
 Allow multiple boot components.

### PR DESCRIPTION
**Pull request by djanowski**

### CODE REVIEW

**Comment by jonathanong** [comment]
i'm probably going to redo this thing after i release component v1

**Comment by remoe** [comment]
:+1:

**Comment by djanowski** [comment]
Redoing sounds good :)

But what do you mean?

There will be no way of specifying which of the bundles are 'bootable'?

**Comment by jonathanong** [comment]
i mean i don't want to take PRs right now until i update all the dependencies to component v1's dependencies. 

i'm also not totally sure what this does. can you give me an example?

**Comment by djanowski** [comment]
OK, no problem.

As we discussed in #2, currently you assume that there's a single boot component. In my case I have a few. This makes it so that you can do in the config:

```
  ...
  boot: "boot",
  ...
```

Or

```
  ...
  boot: ["base", "admin"],
  ...
```

**Comment by jonathanong** [comment]
are these two entirely separate boot components or two different bundles? imo you should always create bundles to save space, but creating two entirely separate boot components is probably easier in general

**Pull request closed without merging**
